### ISSUE TITLE
Spring Data Authentication

### ISSUE THREAD

**Issue by eruiz** [DISID/springlets#1]
`UserDetailsService` that can obtain authentication information from a given JPA entities. Internally Spring Data is used.

This feature provides your Spring Boot application with the security domain model below:
- `@Entity UserLogin`
- `@Entity LoginRole`
- `UserLoginPassword` (DTO)
- `UserLoginRole` (DTO)
- UserLoginDetails (really needed? can we use ApplicationUserDetails instead?)

Note you can create a relation with UserLogin easily in order to integrate that security domain model with the application domain model.

Classes to integrate with Spring Security:
- `ApplicationUserDetails implements UserDetails`
- `@Service ApplicationUserDetailsService implements UserDetailsService`
- ...

Moreover it provides the needed artifacts 
- View layer
  - LoginController
  - /login view, /login?logout, etc.
  - ...
- Service layer
  - `UserLoginService`
  - `UserLoginRoleService`
- Repository layer
  - `UserLoginRepository`
  - `UserLoginRoleRepository`

Finally:
- Spring Boot Starter that registers the needed artifacts easily
- A set of application properties will be provided in order to map this security domain model to custom database shemas:
  - `springlets.security.domain.users.table-name`
  - `springlets.security.domain.users.id-column-name`
  - ...

**Comment by jcagarcia** [comment]
To be able to follow OWASP Security Conventions is necessary to include the following elements in Springlets Security Authentication.

* Add new service  to manage login attempts using a cache.
** Include `LoginAttemptService.java`

* Add properties to handle the maximum number of login attempts.
** Include autoconfiguration for `application.spring.security.login.max-attempts`

* Add properties to handle the days that the cache takes to expire.
** Include autoconfiguration for `application.spring.security.login.days-expire-cache`

* Add listeners to obtain successful login attempts and failure login attempts.
** Include `SpringletsAuthenticationFailureListener.java` and `NorthWindAuthenticationSuccessListener.java`

* Register previous listeners on `SpringletsWebSecurityConfiguration` class.

* Add properties to manage session
** Include `server.session.tracking-modes`, `server.session.cookie.http-only`, `server.session.cookie.secure` and  `server.session.cookie.name`

* Add properties to manage SSL 
** Include `server.ssl.enabled` and `server.ssl.*`

* Use `BCrypt` to encode password
** Update `SpringletsWebSecurityConfigurerAdapter` with `.passwordEncoder(new BCryptPasswordEncoder());`

* Manage `InvalidCsrfTokenException` exception.

* Check `HiddenHttpMethodFilter` filter before Spring Security filter.

**Comment by jcagarcia** [comment]
Created issue #34 to be sure that Springlets follows the OWASP Security conventions
