### ISSUE TITLE
Publish to maven central repository

### ISSUE THREAD

**Issue by eruiz** [DISID/springlets#2]
Upload the Springlets artifacts to the Maven Central Repository.

**Comment by jcagarcia** [comment]
I've just create a new petition to add the _Springlets_ project to Maven Central Repository.

Check https://issues.sonatype.org/browse/OSSRH-25562 to get more info.

**Comment by jcagarcia** [comment]
Springlets project has been created on the Maven Central Repository.

I've just prepare the Springlets project in the following commit to be able to deploy it on maven central:

https://github.com/DISID/springlets/commit/5fbda9ae183848883058e45f331da3855a3b7de1

Also, I've made the first deploy to the snapshot repository:

https://oss.sonatype.org/content/repositories/snapshots/io/springlets/
