### ISSUE TITLE
JSONP support

### ISSUE THREAD

**Issue by eruiz** [DISID/springlets#4]
Advice to configure the JSONP support easily.

It configures the advice below in your application:

```java
@ControllerAdvice
public class JsonpAdvice extends AbstractJsonpResponseBodyAdvice {

  public JsonpAdvice() {
    super("callback");
  }
}
```

It provides the needed application properties to customize JSONP support.

Additionaly the Spring Boot Springlets Starter for MVC will configure this feature automatically.

**Comment by miborra** [comment]
Added JSONP Support through JsopAdvice.
Can configure the callback function with the parameter 'springlets.mvc.advices.jsonp.query-param-names' into application.properties file

Solved in commit https://github.com/DISID/springlets/commit/7b2bae34d26005c21cec7572998c2e97ae4238e9
