### ISSUE TITLE
Sonar vulnerabilities in DatatablesSortHandlerMethodArgumentResolver.java class

### ISSUE THREAD

**Issue by jcagarcia** [DISID/springlets#60]
The following vulnerabilities appear in Sonar when it analizes the `DatatablesSortHandlerMethodArgumentResolver.java` class:

* The regular expression "order\\[([0-9]*)?\\]\\[column\\]" is vulnerable to a denial of service attack (ReDOS)

**Comment by jmvivo** [comment]
Already fixed in 6849b3f
